<?php
/*
Preset: calgary
*/


return $preset_opts = array ( 

'pr_primary_font' => 'Yanone Kaffeesatz',
'pr_secondary_font' => 'Oxygen',
'pr_thumb_cols' => 'column-6',
'pr_thumb_shape' => 'pr-thumb-land',
'pr_thumb_hover' => 'hover-1',
'pr_caption_shape' => 'shape-6',
'pr_caption_shape_animation' => 'entry-caption-1',
'pr_caption_shape_amination_speed' => 'animated-1',
'pr_caption_shape_bgcolor' => 'rgba(255,255,255,0.8)',
'pr_caption_permalink_icon' => '1',
'pr_caption_title_color' => '#ffffff',
'pr_caption_title_size' => '35',
'pr_caption_title_weight' => '400',
'pr_caption_title_style' => 'normal',
'pr_caption_subtitle_source' => 'excerpt',
'pr_caption_subtitle_bgcolor' => 'rgba(51,51,51,1)',
'pr_caption_subtitle_color' => '#ff0000',
'pr_caption_subtitle_size' => '20',
'pr_caption_subtitle_weight' => '300',
'pr_caption_subtitle_style' => 'normal',
'pr_caption_metas' => '1',
'pr_caption_metas_color' => '#ffffff',
'pr_caption_metas_size' => '14',
'pr_caption_metas_weight' => '300',
'pr_caption_metas_style' => 'normal',
'pr_excerpt_style' => 'excerpt-4',
'pr_excerpt_bg' => 'rgba(255,255,255,1)',
'pr_excerpt_header_color' => '#222222',
'pr_excerpt_header_over_color' => '#cccccc',
'pr_excerpt_header_size' => '22',
'pr_excerpt_header_weight' => '400',
'pr_excerpt_header_style' => 'normal',
'pr_excerpt_content_color' => '#666666',
'pr_excerpt_content_size' => '14',
'pr_excerpt_content_weight' => '300',
'pr_excerpt_content_style' => 'normal',
'pr_excerpt_button_text' => 'Read More',
'pr_excerpt_button_color' => '#333333',
'pr_excerpt_button_size' => '14',
'pr_excerpt_button_weight' => '300',
'pr_excerpt_button_style' => 'normal',
'pr_preview_enable' => '1',
'pr_preview_style' => 'preview-overlay-3',
'pr_preview_animation' => 'entry-preview-3',
'pr_preview_speed' => 'animated-1',
'pr_preview_drag' => '1',
'pr_preview_title_color' => '#222222',
'pr_preview_title_size' => '50',
'pr_preview_title_weight' => '400',
'pr_preview_title_style' => 'normal',
'pr_preview_subtitle_bgcolor' => '#333333',
'pr_preview_subtitle_color' => '#ffffff',
'pr_preview_subtitle_size' => '35',
'pr_preview_subtitle_weight' => '300',
'pr_preview_subtitle_style' => 'normal',
'pr_preview_content_color' => '#666666',
'pr_preview_content_size' => '14',
'pr_preview_content_weight' => '300',
'pr_preview_content_style' => 'normal',

);