<?php
/*
Preset: rome
*/


return $preset_opts = array ( 

'pr_primary_font' => 'Noto Serif',
'pr_secondary_font' => 'Roboto Condensed',
'pr_thumb_cols' => 'column-5',
'pr_thumb_shape' => 'pr-thumb-square',
'pr_thumb_hover' => 'hover-1',
'pr_caption_shape' => 'shape-4',
'pr_caption_shape_animation' => 'entry-caption-8',
'pr_caption_shape_amination_speed' => 'animated-1',
'pr_caption_shape_bgcolor' => 'rgba(150,40,27,0.7)',
'pr_caption_permalink_icon' => '1',
'pr_caption_title_color' => '#ffffff',
'pr_caption_title_size' => '28',
'pr_caption_title_weight' => '400',
'pr_caption_title_style' => 'normal',
'pr_caption_subtitle_source' => 'excerpt',
'pr_caption_subtitle_bgcolor' => 'rgba(255,255,255,1)',
'pr_caption_subtitle_color' => '#96281b',
'pr_caption_subtitle_size' => '16',
'pr_caption_subtitle_weight' => '300',
'pr_caption_subtitle_style' => 'normal',
'pr_caption_metas' => '',
'pr_caption_metas_color' => '#ffffff',
'pr_caption_metas_size' => '16',
'pr_caption_metas_weight' => '300',
'pr_caption_metas_style' => 'normal',
'pr_excerpt_style' => '',
'pr_excerpt_bg' => '',
'pr_excerpt_header_color' => '#222222',
'pr_excerpt_header_over_color' => '#96281b',
'pr_excerpt_header_size' => '16',
'pr_excerpt_header_weight' => '400',
'pr_excerpt_header_style' => 'normal',
'pr_excerpt_content_color' => '#666666',
'pr_excerpt_content_size' => '18',
'pr_excerpt_content_weight' => '300',
'pr_excerpt_content_style' => 'normal',
'pr_excerpt_button_text' => 'More',
'pr_excerpt_button_color' => '#96281b',
'pr_excerpt_button_size' => '14',
'pr_excerpt_button_weight' => '300',
'pr_excerpt_button_style' => 'normal',
'pr_preview_enable' => '1',
'pr_preview_style' => 'preview-overlay-2',
'pr_preview_animation' => 'entry-preview-7',
'pr_preview_speed' => 'animated-1',
'pr_preview_drag' => '1',
'pr_preview_title_color' => '#333333',
'pr_preview_title_size' => '50',
'pr_preview_title_weight' => '400',
'pr_preview_title_style' => 'normal',
'pr_preview_subtitle_bgcolor' => '#96281b',
'pr_preview_subtitle_color' => '#ffffff',
'pr_preview_subtitle_size' => '30',
'pr_preview_subtitle_weight' => '300',
'pr_preview_subtitle_style' => 'normal',
'pr_preview_content_color' => '#333333',
'pr_preview_content_size' => '14',
'pr_preview_content_weight' => '300',
'pr_preview_content_style' => 'normal',

);