<?php
/*
Preset: seul
*/


return $preset_opts = array ( 

'pr_primary_font' => 'Ubuntu',
'pr_secondary_font' => 'Lora',
'pr_thumb_cols' => 'column-3',
'pr_thumb_shape' => 'pr-thumb-land',
'pr_thumb_hover' => 'hover-2',
'pr_caption_shape' => 'shape-5',
'pr_caption_shape_animation' => 'entry-caption-1',
'pr_caption_shape_amination_speed' => 'animated-1',
'pr_caption_shape_bgcolor' => 'rgba(31,58,147,0.7)',
'pr_caption_permalink_icon' => '1',
'pr_caption_title_color' => '#ffffff',
'pr_caption_title_size' => '34',
'pr_caption_title_weight' => '400',
'pr_caption_title_style' => 'normal',
'pr_caption_subtitle_source' => 'categories',
'pr_caption_subtitle_bgcolor' => 'rgba(255,255,255,1)',
'pr_caption_subtitle_color' => '#1f3a93',
'pr_caption_subtitle_size' => '20',
'pr_caption_subtitle_weight' => '300',
'pr_caption_subtitle_style' => 'normal',
'pr_caption_metas' => '1',
'pr_caption_metas_color' => '#ffffff',
'pr_caption_metas_size' => '14',
'pr_caption_metas_weight' => '300',
'pr_caption_metas_style' => 'normal',
'pr_excerpt_style' => '',
'pr_excerpt_bg' => 'rgba(255,255,255,1)',
'pr_excerpt_header_color' => '#222222',
'pr_excerpt_header_over_color' => '#1f3a93',
'pr_excerpt_header_size' => '22',
'pr_excerpt_header_weight' => '400',
'pr_excerpt_header_style' => 'normal',
'pr_excerpt_content_color' => '#666666',
'pr_excerpt_content_size' => '14',
'pr_excerpt_content_weight' => '300',
'pr_excerpt_content_style' => 'normal',
'pr_excerpt_button_text' => 'Read All',
'pr_excerpt_button_color' => '#1f3a93',
'pr_excerpt_button_size' => '14',
'pr_excerpt_button_weight' => '300',
'pr_excerpt_button_style' => 'normal',
'pr_preview_enable' => '1',
'pr_preview_style' => 'preview-overlay-3',
'pr_preview_animation' => 'entry-preview-9',
'pr_preview_speed' => 'animated-2',
'pr_preview_drag' => '1',
'pr_preview_title_color' => '#222222',
'pr_preview_title_size' => '50',
'pr_preview_title_weight' => '400',
'pr_preview_title_style' => 'normal',
'pr_preview_subtitle_bgcolor' => '#1f3a93',
'pr_preview_subtitle_color' => '#ffffff',
'pr_preview_subtitle_size' => '30',
'pr_preview_subtitle_weight' => '300',
'pr_preview_subtitle_style' => 'normal',
'pr_preview_content_color' => '#666666',
'pr_preview_content_size' => '14',
'pr_preview_content_weight' => '300',
'pr_preview_content_style' => 'normal',

);