<?php
/*
Preset: tokyo
*/


return $preset_opts = array ( 

'pr_primary_font' => 'Jura',
'pr_secondary_font' => 'Fjalla One',
'pr_thumb_cols' => 'column-5',
'pr_thumb_shape' => 'random',
'pr_thumb_hover' => 'hover-1',
'pr_caption_shape' => 'shape-14',
'pr_caption_shape_animation' => 'entry-caption-8',
'pr_caption_shape_amination_speed' => 'animated-1',
'pr_caption_shape_bgcolor' => 'rgba(255,255,255,0.7)',
'pr_caption_permalink_icon' => '1',
'pr_caption_title_color' => '#d91e18',
'pr_caption_title_size' => '32',
'pr_caption_title_weight' => '600',
'pr_caption_title_style' => 'normal',
'pr_caption_subtitle_source' => 'excerpt',
'pr_caption_subtitle_bgcolor' => 'rgba(34,34,34,1)',
'pr_caption_subtitle_color' => '#ffffff',
'pr_caption_subtitle_size' => '20',
'pr_caption_subtitle_weight' => '300',
'pr_caption_subtitle_style' => 'normal',
'pr_caption_metas' => '1',
'pr_caption_metas_color' => '#222222',
'pr_caption_metas_size' => '14',
'pr_caption_metas_weight' => '300',
'pr_caption_metas_style' => 'normal',
'pr_excerpt_style' => '0',
'pr_excerpt_bg' => '',
'pr_excerpt_header_color' => '#222222',
'pr_excerpt_header_over_color' => '',
'pr_excerpt_header_size' => '22',
'pr_excerpt_header_weight' => '400',
'pr_excerpt_header_style' => 'normal',
'pr_excerpt_content_color' => '#666666',
'pr_excerpt_content_size' => '14',
'pr_excerpt_content_weight' => '300',
'pr_excerpt_content_style' => 'normal',
'pr_excerpt_button_text' => 'Read More',
'pr_excerpt_button_color' => '#333333',
'pr_excerpt_button_size' => '14',
'pr_excerpt_button_weight' => '300',
'pr_excerpt_button_style' => 'normal',
'pr_preview_enable' => '1',
'pr_preview_style' => 'preview-overlay-3',
'pr_preview_animation' => 'entry-preview-9',
'pr_preview_speed' => 'animated-1',
'pr_preview_drag' => '1',
'pr_preview_title_color' => '#222222',
'pr_preview_title_size' => '50',
'pr_preview_title_weight' => '400',
'pr_preview_title_style' => 'normal',
'pr_preview_subtitle_bgcolor' => '#d91e18',
'pr_preview_subtitle_color' => '#ffffff',
'pr_preview_subtitle_size' => '30',
'pr_preview_subtitle_weight' => '300',
'pr_preview_subtitle_style' => 'normal',
'pr_preview_content_color' => '#666666',
'pr_preview_content_size' => '14',
'pr_preview_content_weight' => '300',
'pr_preview_content_style' => 'normal',

);